name: Release

on:
  push:
    branches:
      - master
      - releases

jobs:      
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: make all
        
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
          files: |
            dist/George_Messiha_Resume.pdf
            dist/George_Messiha_CoverLetter.pdf
            dist/George_Messiha_detailed_resume.pdf
