name: Release

on:
  push:
    branches:
      - master
      - releases

jobs:      
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: make all
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.3.1
        id: tags
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.tags.outputs.changelog }}
          tag_name: ${{ steps.tags.outputs.new_tag }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            dist/George_Messiha_Resume.pdf
            dist/George_Messiha_CoverLetter.pdf
            dist/George_Messiha_detailed_resume.pdf
